---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: <project>
spec:
  rules:
    - host: example.com
	  http:
	    paths:
		  - path: /testpath
		    backend:
			  serviceName: test
			  servicePort: 80